apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: apollo-router-latency-p95
spec:
  groups:
    - name: ApolloRouterAlerts
      interval: 1m0s
      rules:
        - alert: ApolloRouterLatencyP95High
          expr: histogram_quantile(0.95, rate(http_server_request_duration_bucket{service_name="${router_service_name}"}[5m])) * 1000 > ${latency_p95_threshold}
          for: 3m
          annotations:
            summary: "Apollo Router P95 latency is above ${latency_p95_threshold}ms"
            description: "Latency {{$$value | printf \"%.0f\"}}ms exceeded threshold"
            dash0-threshold-critical: "${latency_p95_threshold_critical}"
            dash0-threshold-degraded: "${latency_p95_threshold}"
            dash0-enabled: "true"
          labels:
            severity: warning
            env: ${environment}

