apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: apollo-router-error-rate
spec:
  groups:
    - name: ApolloRouterAlerts
      interval: 1m0s
      rules:
        - alert: ApolloRouterErrorRateHigh
          expr: ((rate(http_server_request_duration_bucket{service_name="${router_service_name}",http_response_status_code=~"[45].."}[5m])) / (rate(http_server_request_duration_bucket{service_name="${router_service_name}"}[5m]))) * 100 > ${error_rate_threshold}
          for: 2m
          annotations:
            summary: "Apollo Router error rate is above ${error_rate_threshold}%"
            description: "Error rate {{$$value | printf \"%.2f\"}}% exceeded threshold"
            dash0-threshold-critical: "${error_rate_threshold_critical}"
            dash0-threshold-degraded: "${error_rate_threshold}"
            dash0-enabled: "true"
          labels:
            severity: warning
            env: ${environment}

