apiVersion: operator.dash0.com/v1beta1
kind: Dash0Monitoring
metadata:
  name: dash0-operator-configuration
  namespace: apollo-dash0-demo
spec:
  # Instrumentation configuration for workloads
  instrumentWorkloads:
    # Mode: none = disable auto-instrumentation (applications are manually instrumented)
    # Other modes: "all" = instrument all workloads, "created-and-updated" = instrument new/updated workloads
    mode: none

    # Label selector: only instrument workloads that explicitly opt-in with dash0.com/enable=true
    labelSelector: "dash0.com/enable=true"

  # Log collection settings
  logCollection:
    enabled: true

  # Prometheus scraping settings
  prometheusScraping:
    enabled: false

  # Synchronize Perses dashboards with Dash0
  synchronizePersesDashboards: true

  # Synchronize Prometheus rules with Dash0
  synchronizePrometheusRules: true

  # Export configuration (inherits from operator config by default)
  # No need to specify - will use the cluster-wide Dash0OperatorConfiguration
