apiVersion: operator.dash0.com/v1alpha1
kind: Dash0OperatorConfiguration
metadata:
  name: dash0-operator-configuration
spec:
  # Use HTTP export instead of gRPC to avoid authentication token blocking issues
  # The operator's gRPC endpoint (port 4317) may block certain auth tokens,
  # while the HTTP endpoint (port 443/4318) works reliably
  export:
    http:
      # Base OTLP HTTP endpoint - the exporter will append /v1/traces, /v1/metrics, /v1/logs
      endpoint: https://ingress.us-west-2.aws.dash0.com
      headers:
        - name: Authorization
          value: Bearer auth_nGhIW24mv8kWSH6uz19Ig8hhSdwOYKA7
        # Dash0 dataset specification
        # NOTE: To change the dataset, update this value AND update DASH0_DATASET in the apollo-config ConfigMap
        # The ConfigMap value is used by the Apollo Router
        # This value is used by the Dash0 Operator for Kubernetes infrastructure telemetry
        - name: Dash0-Dataset
          value: gtm-dash0
      encoding: proto  # Use protobuf encoding (can be "proto" or "json")

  # Enable collection of Kubernetes infrastructure metrics
  kubernetesInfrastructureMetricsCollection:
    enabled: true

  # Enable telemetry collection from instrumented workloads (metrics, traces, logs)
  telemetryCollection:
    enabled: true

  # Enable operator self-monitoring
  selfMonitoring:
    enabled: true

  # Collect pod labels and annotations for enrichment
  collectPodLabelsAndAnnotations:
    enabled: true
