---
# Dash0 Monitoring Resource
# Configures automatic instrumentation for workloads in the apollo-dash0-demo namespace
# Documentation: https://github.com/dash0hq/dash0-operator/tree/main/helm-chart/dash0-operator#disabling-auto-instrumentation-for-specific-workloads
apiVersion: operator.dash0.com/v1beta1
kind: Dash0Monitoring
metadata:
  name: dash0-monitoring-resource
  namespace: apollo-dash0-demo
spec:
  # Instrumentation configuration for workloads
  instrumentWorkloads:
    # Mode: none = disable auto-instrumentation (applications are manually instrumented)
    # Other modes: "all" = instrument all workloads, "created-and-updated" = instrument new/updated workloads
    mode: none

    # Label selector: only instrument workloads that explicitly opt-in with dash0.com/enable=true
    # See docs link above for more information on disabling auto-instrumentation
    labelSelector: "dash0.com/enable=true"

  # Log collection settings
  logCollection:
    enabled: true

  # Prometheus scraping settings
  prometheusScraping:
    enabled: false

  # Synchronize Perses dashboards with Dash0
  synchronizePersesDashboards: true

  # Synchronize Prometheus rules with Dash0
  synchronizePrometheusRules: true

  # Export configuration (inherits from operator config by default)
  # No need to specify - will use the cluster-wide Dash0OperatorConfiguration
