apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apollo-dash0-demo

resources:
  - dash0-monitoring.yaml
  - vegeta.yaml
  - subgraphs/accounts.yaml
  - subgraphs/inventory.yaml
  - subgraphs/products.yaml
  - subgraphs/reviews.yaml